### PR TITLE
Report #require directive errors

### LINKED ISSUE #200: Report #require directive errors
Until we have a better way to handle toplevel fragments we need to report errors from `#require` directive.

Currently what happens is that the directive can fail silently and the error mode is a quite unhelpful `Unbound module X` message.

The way `Topfind` report errors isn't great as it simply prints them to stdout but it seems that we're somehow capturing those.

Hopefully that won't be a problem in the future as we won't rely on those directives to use packages in the toplevel but until then it would prove very helpful to debug issues in RWO which relies on master!

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #200 
I don't like the idea of testing the literal string of the output to decide whether it's an error, but there is no return code or whatever.

### CODE REVIEW

**Comment by gpetiot** [comment]
That's a good idea, I did this in the last commit. Although it's not possible to raise exceptions from this and hoping they are caught in our eval function, so I had to resort at making the errors reference global so it is toggled in case the require directive failed.

File: lib/top/mdx_top.ml [hunk 1]
```diff
@@ -591,6 +616,11 @@ let init ~verbose:v ~silent:s ~verbose_findlib () =
   Topfind.don't_load_deeply
     [ "unix"; "findlib.top"; "findlib.internal"; "compiler-libs.toplevel" ];
   Topfind.add_predicates [ "byte"; "toploop" ];
+  (* [require] directive is overloaded to toggle the [errors] reference when
+     an exception is raised. *)
+  Hashtbl.add Toploop.directive_table "require"
```
Comment (Julow) [inline lib/top/mdx_top.ml:621]:
```suggestion
  Hashtbl.replace Toploop.directive_table "require"
```

This may not be useful, I don't expect a directive to be removed.
